/*
NONG HOANG VU_PH33506
LAB 5 + 6
THUC HANH SP: SU DUNG DB QLDA
*/
USE QLDA
GO

/*____________________________________________________________________________________________________________________*/
-- TAO SP DE THEM 1 THAN NHAN (1)
CREATE PROC SP_THEMTHANNHAN
@MA_NVIEN NVARCHAR(9),
@TENTN NVARCHAR(15),
@PHAI NVARCHAR(3),
@NGSINH DATE,
@QUANHE NVARCHAR(15)
AS BEGIN
	INSERT INTO THANNHAN VALUES(@MA_NVIEN, @TENTN, @PHAI, @NGSINH, @QUANHE)
END
EXEC SP_THEMTHANNHAN '005',N'CAT', N'Nam', '2000-12-02', N'Người yêu'

/*____________________________________________________________________________________________________________________*/
-- TAO SP DE UPDATE PHAI CUA NV DUOC CHON (2)
CREATE PROC SP_CAPNHATPHAICUANV
@MANV NVARCHAR(9),
@PHAI NVARCHAR(3)
AS BEGIN
	IF EXISTS(SELECT * FROM NHANVIEN WHERE MANV = @MANV)
	BEGIN
		DECLARE @GENDER NVARCHAR(3);

		IF (@PHAI = 'nam' OR @PHAI = 'NAM' OR @PHAI = 'Nam' OR @PHAI = 'nAM' OR @PHAI = 'nấm' OR LOWER(@PHAI) = 'nấm' OR LOWER(@PHAI) = 'nam' OR @PHAI = 'Nấm' OR @PHAI = 'NAM' OR @PHAI = 'NÂM' OR LOWER(@PHAI) = 'nÂm')
		BEGIN
			SET @GENDER = N'Nam'
		END
		ELSE
		BEGIN
			IF (@PHAI = 'nu' OR @PHAI = 'NU' OR @PHAI = 'Nu' OR @PHAI = 'nU' OR @PHAI = 'nư' OR LOWER(@PHAI) = 'nữ' OR LOWER(@PHAI) = 'nu' OR @PHAI = 'nư' OR @PHAI = 'nƯ' OR @PHAI = 'Nư' OR @PHAI = 'NỮ' OR LOWER(@PHAI) = 'nỮ')
			BEGIN
				SET @GENDER = N'Nữ'
			END
			ELSE
			BEGIN
				SET @GENDER = null
			END
		END

		UPDATE NHANVIEN
		SET PHAI = @GENDER
		WHERE @MANV = MANV
	END
	ELSE
	BEGIN
		DECLARE @MESSAGE NVARCHAR(100) = 'KHONG TIM THAY NHAN VIEN ' + CAST(@MANV AS NVARCHAR)
		RAISERROR(@MESSAGE, 16, 16)
	END
END
EXEC SP_CAPNHATPHAICUANV '009', N'NAM'

/*____________________________________________________________________________________________________________________*/
-- TAO SP DE XOA 1 THAN NHAN (2)
CREATE PROC SP_XOA1THANNHAN
@TENTN NVARCHAR(15)
AS BEGIN
	IF EXISTS(SELECT * FROM THANNHAN WHERE TENTN LIKE @TENTN)
	BEGIN
		DELETE FROM THANNHAN WHERE TENTN = @TENTN
		RAISERROR('XOA THANH CONG', 16, 16)
	END
	ELSE
	BEGIN
		DECLARE @MESSAGE NVARCHAR(100) = 'KHONG TIM THAY THAN NHAN ' + CAST(@TENTN AS NVARCHAR)
		RAISERROR(@MESSAGE, 16, 16)
	END
END
EXEC SP_XOA1THANNHAN 'CAT'

/*____________________________________________________________________________________________________________________*/
-- TAO SP DE CHON RA NHUNG NV CO MADA = 1 (2)
CREATE PROC SP_NVMADA1
@MADA INT
AS BEGIN
	DECLARE @COUNT INT;
	SELECT @COUNT = COUNT(DISTINCT NHANVIEN.MANV)
	FROM NHANVIEN JOIN PHANCONG ON PHANCONG.MA_NVIEN = NHANVIEN.MANV INNER JOIN CONGVIEC ON PHANCONG.MADA = CONGVIEC.MADA
	WHERE PHANCONG.MADA = @MADA
	
	IF(NOT @COUNT > 0)
	BEGIN
		DECLARE @MESSAGE NVARCHAR(100) = 'KHONG CO NHAN VIEN CO MADA LA ' + CAST(@MADA AS NVARCHAR)
		RAISERROR(@MESSAGE, 16, 16)
	END
	ELSE
	BEGIN
		SELECT DISTINCT  NHANVIEN.HONV, NHANVIEN.TENLOT, NHANVIEN.TENNV, NHANVIEN.MANV, PHANCONG.MADA
		FROM NHANVIEN JOIN PHANCONG ON PHANCONG.MA_NVIEN = NHANVIEN.MANV
		INNER JOIN CONGVIEC ON PHANCONG.MADA = CONGVIEC.MADA
		WHERE PHANCONG.MADA = @MADA
	END
END
EXEC SP_NVMADA1 1

/*____________________________________________________________________________________________________________________*/
-- TAO SP CHON RA NV THEO KHOANG LUONG
CREATE PROC SP_NVTHEOKHOANGLUONG
@MIN INT,
@MAX INT
AS BEGIN
	IF(@MIN > @MAX)
	BEGIN
		RAISERROR('GIA TRI LUONG KHONG HOP LE', 16, 16)
	END
	ELSE
	BEGIN
		SELECT * FROM NHANVIEN WHERE LUONG >= @MIN AND LUONG <= @MAX
	END
END
EXEC SP_NVTHEOKHOANGLUONG 25000, 40000

/*____________________________________________________________________________________________________________________*/
-- TAO VIEW CHON RA NV VA CHUC VU CUA HO CO CHUC VU LA TRUONG PHONG (BIET TRUONG PHONG CO LUONG > 35000) (1)
ALTER VIEW VIEW_NVLATRUONGPHONG
AS
SELECT HONV, TENLOT, TENNV, MANV, NGSINH, DCHI, PHAI, LUONG, MA_NQL, PHG, IIF(LUONG > 35000, N'Trưởng phòng', N'Nhân viên') AS N'Chức vụ' FROM NHANVIEN WHERE LUONG > 35000

SELECT * FROM VIEW_NVLATRUONGPHONG
