USE NHAMAY
GO
-- PHONG
CREATE TABLE PHONG(
	MaPHG NCHAR(10) PRIMARY KEY NOT NULL,
	TenPHG NVARCHAR(50) NOT NULL,
	NamBatDau INT NOT NULL
)
-- CONGNHAN
CREATE TABLE CONGNHAN(
	MaNV NCHAR(10) PRIMARY KEY NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	NgaySinh DATE,
	GioiTinh NVARCHAR(3) NOT NULL
)
-- KHENTHUONG
CREATE TABLE KHENTHUONG(
	MaNV NCHAR(10) NOT NULL,
	MaPHG NCHAR(10) NOT NULL,
	SoTien INT NOT NULL,
	FOREIGN KEY (MaNV) REFERENCES CONGNHAN(MaNV),
	FOREIGN KEY (MaPHG) REFERENCES PHONG(MaPHG)
)
-- INSERT PHONG
CREATE PROCEDURE SP_INSER_PHONG
	@MaPHG NCHAR(10),
	@TenPHG NVARCHAR(50),
	@NamBatDau INT
AS BEGIN
	IF (@MaPHG IS NULL OR @TenPHG IS NULL OR @NamBatDau IS NULL)
	BEGIN
		RAISERROR('DU LIEU KHONG HOP LE', 16, 16)
	END ELSE BEGIN
		INSERT INTO PHONG VALUES (@MaPHG, @TenPHG, @NamBatDau)
		PRINT 'THEM THANH CONG'
	END
END
EXEC SP_INSER_PHONG 'P1', 'PHONG A', 2021
EXEC SP_INSER_PHONG 'P2', 'PHONG B', 2022
EXEC SP_INSER_PHONG 'P3', 'PHONG C', 2023
SELECT * FROM PHONG

-- INSERT CONGNHAN
CREATE PROCEDURE SP_INSERT_CONGNHAN
	@MaNV NCHAR(10),
	@HoTen NVARCHAR(50),
	@NgaySinh DATE,
	@GioiTinh NVARCHAR(3)
AS BEGIN
	IF(@MaNV IS NULL OR @HoTen IS NULL OR @NgaySinh IS NULL OR @GioiTinh IS NULL)
	BEGIN
		RAISERROR('DU LIEU KHONG HOP LE', 16, 16)
	END ELSE BEGIN
		INSERT INTO CONGNHAN VALUES (@MaNV, @HoTen, @NgaySinh, @GioiTinh)
		PRINT 'THEM THANH CONG'
	END
END
SELECT * FROM CONGNHAN
EXEC SP_INSERT_CONGNHAN 'NV01','Nguyen Van A','1990-01-01','NAM'
EXEC SP_INSERT_CONGNHAN 'NV02','Tran Thi B','1995-05-10','NU'
EXEC SP_INSERT_CONGNHAN 'NV03','Pham Van C','1988-12-15','NAM'

-- INSERT KHENTHUONG
CREATE PROCEDURE SP_INSER_KHENTHUONG
	@MaNV NCHAR(10),
	@MaPHG NCHAR(10),
	@SoTien INT
AS BEGIN
	IF(@MaNV IS NULL OR @MaPHG IS NULL OR @SoTien IS NULL)
	BEGIN
		RAISERROR('DU LIEU KHONG HOP LE', 16, 16)
	END ELSE BEGIN
		INSERT INTO KHENTHUONG VALUES (@MaNV, @MaPHG, @SoTien)
		PRINT 'THEM THANH CONG'
	END
END
SELECT * FROM KHENTHUONG
EXEC SP_INSER_KHENTHUONG 'NV02', 'P3', 500000
EXEC SP_INSER_KHENTHUONG 'NV01', 'P2', 1000000
EXEC SP_INSER_KHENTHUONG 'NV03', 'P1', 800000

-- CAU 3: HAM TRA VE MaNV
ALTER FUNCTION FN_GET_MaNV(@HoTen NVARCHAR(50),@NgaySinh DATE, @GioiTinh NVARCHAR(3))
	RETURNS NCHAR(50)
AS BEGIN
	DECLARE @MaNV NCHAR(10)
	IF EXISTS(SELECT MaNV FROM CONGNHAN WHERE @HoTen LIKE HoTen AND @NgaySinh LIKE NgaySinh AND @GioiTinh LIKE GioiTinh)
	BEGIN
		SELECT @MaNV = MaNV FROM CONGNHAN WHERE @HoTen LIKE HoTen AND @NgaySinh LIKE NgaySinh AND @GioiTinh LIKE GioiTinh
		RETURN @MaNV
	END
	RETURN 'KHONG TIM THAY'

END
PRINT DBO.FN_GET_MaNV('Nguyen Van A', '1990-01-01', 'NAM')
PRINT DBO.FN_GET_MaNV('Nguyen Van A', '1990-01-01', 'NU')

-- CAU 4: VIEW TOP 2 CO GT TIEN LON NHAT
CREATE VIEW VW_TOP2_MAX_SoTien AS
SELECT TOP 2 CONGNHAN.MaNV, CONGNHAN.HoTen, KHENTHUONG.SoTien FROM CONGNHAN INNER JOIN KHENTHUONG ON CONGNHAN.MaNV = KHENTHUONG.MaNV ORDER BY KHENTHUONG.SoTien DESC
--
SELECT * FROM VW_TOP2_MAX_SoTien

-- CAU 5: 
CREATE PROCEDURE SP_DELETE_ITEM
	@TongTien INT
AS BEGIN TRY
	DECLARE @THONGTIN TABLE (MaNV NCHAR(10))
	INSERT INTO @THONGTIN
	SELECT MaNV FROM KHENTHUONG WHERE KHENTHUONG.SoTien > @TongTien
	BEGIN TRAN
		DELETE FROM KHENTHUONG WHERE KHENTHUONG.MaNV IN (SELECT * FROM @THONGTIN)
		DELETE FROM CONGNHAN WHERE CONGNHAN.MaNV IN (SELECT * FROM @THONGTIN)
		PRINT 'XOA THANH CONG'
	COMMIT TRAN
END TRY
BEGIN CATCH
	ROLLBACK TRAN
	RAISERROR('XOA THAT BAI', 16, 16)
END CATCH
SELECT * FROM CONGNHAN INNER JOIN KHENTHUONG ON CONGNHAN.MaNV = KHENTHUONG.MaNV
SELECT * FROM KHENTHUONG
EXEC SP_DELETE_ITEM 400000