-- CREATE TABLE THANNHAN
CREATE TABLE THANNHAN(
	MaTN NCHAR(10) PRIMARY KEY NOT NULL,
	HoTen NVARCHAR(255) NOT NULL,
	NamSinh INT NOT NULL,
	GTinh NCHAR(4) NOT NULL
)
-- ADD DATA TO THANNHAN
INSERT INTO THANNHAN(MaTN, HoTen, NamSinh, GTinh)
VALUES
	('TN1', 'DUONG THI THUY', 1988, 'NU'),
	('TN2', 'NGUYEN QUYNH', 2005, 'NU'),
	('TN3', 'LE TRONG TAN', 1980, 'NAM');

-- CREATE TABLE NHANVIEN
CREATE TABLE NHANVIEN(
	Ma NCHAR(10) PRIMARY KEY NOT NULL,
	HoTen NVARCHAR(255) NOT NULL,
	NamSinh INT NOT NULL,
	Luong INT
)
-- ADD DATA FOR NHANVIEN
INSERT INTO NHANVIEN(Ma, HoTen, NamSinh, Luong)
VALUES
	('NV1', 'NGUYEN VAN A', 1980, 5000),
	('NV2', 'LE VAN B', 1987, 4000),
	('NV3', 'PHAM THI C', 1985, 3000);
--CREATE TABLE PHUCAP
CREATE TABLE PHUCAP(
	MASO NCHAR(10) PRIMARY KEY NOT NULL,
	MANV NCHAR(10) NOT NULL,
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(Ma),
	MATN NCHAR(10) NOT NULL,
	FOREIGN KEY (MATN) REFERENCES THANNHAN(MaTN),
	PHUCAP INT	
)
-- ADD DATA FOR PHUCAP
INSERT INTO PHUCAP(MASO, MANV, MATN, PHUCAP)
VALUES
	('PC01', 'NV1', 'TN1', 200),
	('PC02', 'NV1', 'TN1', 500),
	('PC03', 'NV3', 'TN3', 300);

-- L2
SELECT NV.Ma, NV.HoTen, NV.NamSinh, NV.Luong FROM NHANVIEN NV
JOIN PHUCAP PC ON PC.MANV = NV.Ma WHERE PC.PHUCAP < 300

--L3
SELECT NV.Ma, NV.HoTen, NV.NamSinh, NV.Luong, (YEAR(GETDATE()) - NV.NamSinh) AS TUOI
FROM NHANVIEN NV WHERE (YEAR(GETDATE()) - NV.NamSinh) < 40

--L4
SELECT NV.Ma, NV.HoTen,NV.NamSinh ,SUM(PC.PHUCAP) AS 'TONG PHU CAP' FROM NHANVIEN NV JOIN PHUCAP PC ON NV.Ma = PC.MANV GROUP BY NV.Ma, NV.HoTen, NV.NamSinh
--L5
SELECT TOP 2 MaTN, HoTen, NamSinh, (YEAR(GETDATE()) - NamSinh) AS TUOI
FROM THANNHAN ORDER BY NamSinh ASC

--L6
INSERT INTO THANNHAN(MaTN, HoTen, NamSinh, GTinh)
VALUES('TN4', 'NGUYEN THI E', 1998, 'NU')

--L7
UPDATE PHUCAP
SET PHUCAP = PHUCAP * 0.9

--L8
DELETE FROM NHANVIEN WHERE NOT EXISTS(
	SELECT 1
	FROM THANNHAN WHERE NHANVIEN.Ma = THANNHAN.MaTN
)
