USE LAB3_LAB4
GO

-- BAI 1
CREATE TABLE OTO(
	MA INT PRIMARY KEY NOT NULL,
	TEN NVARCHAR(50) NOT NULL,
	HANG_XE NVARCHAR(50) NOT NULL,
	KIEU_DANG NVARCHAR(50) NOT NULL,
	NAMSX INT NOT NULL,
	GIA_TIEN FLOAT NOT NULL
);
INSERT INTO OTO(MA, TEN, HANG_XE, KIEU_DANG, NAMSX, GIA_TIEN) VALUES
	(1, 'Toyota Camry', 'Toyota', 'Sedan', 2018, 25000.00),
    (2, 'Honda Civic', 'Honda', 'Sedan', 2020, 22000.00),
    (3, 'Ford Mustang', 'Ford', 'Coupe', 2015, 40000.00),
    (4, 'BMW X5', 'BMW', 'SUV', 2019, 55000.00),
    (5, 'Mercedes-Benz C-Class', 'Mercedes-Benz', 'Sedan', 2021, 35000.00);

-- BAI 2
BEGIN
	DECLARE @MA INT, @TEN NVARCHAR(50), @HANG_XE NVARCHAR(50), @KIEU_DANG NVARCHAR(50), @NAMSX INT, @GIA_TIEN FLOAT;
	SET @MA = 6;
	SET @TEN = 'Xe Moi';
	SET @HANG_XE = 'Toyota';
	SET @KIEU_DANG = 'Sedan';
	SET @NAMSX = 2022;
	SET @GIA_TIEN = 150000000;
	INSERT INTO OTO(MA, TEN, HANG_XE, KIEU_DANG, NAMSX, GIA_TIEN) VALUES
	(@MA, @TEN, @HANG_XE, @KIEU_DANG, @NAMSX, @GIA_TIEN);
END
-- BAI 3
--Y1
BEGIN
	DECLARE @HANGXE NVARCHAR(50) = 'Toyota';
	SELECT * FROM OTO WHERE HANG_XE = @HANGXE;
END

--Y2
BEGIN
	DECLARE @NAM_SX INT = 2010;
	SELECT * FROM OTO WHERE NAMSX < @NAM_SX;
END

--Y3
BEGIN
	DECLARE @GIATIENTB FLOAT;
	SELECT @GIATIENTB = AVG(GIA_TIEN) FROM OTO;
	PRINT @GIATIENTB
END

-- BAI 4
BEGIN
	DECLARE @XEMAY TABLE(
		MA INT PRIMARY KEY NOT NULL,
		TEN NVARCHAR(50) NOT NULL,
		HANG_XE NVARCHAR(50) NOT NULL,
		KIEU_DANG NVARCHAR(50) NOT NULL,
		NAMSX INT NOT NULL,
		GIA_TIEN FLOAT NOT NULL
	);
	-- Y1
	INSERT INTO @XEMAY(MA, TEN, HANG_XE, KIEU_DANG, NAMSX, GIA_TIEN) VALUES
	(1, 'Yamaha Exciter', 'Yamaha', 'The Thao', 2020, 3500);

	-- Y2
	DECLARE @XETT NVARCHAR(50) = 'The Thao';
	SELECT * FROM @XEMAY WHERE KIEU_DANG = @XETT

	-- Y3
	UPDATE @XEMAY SET KIEU_DANG = 'Van Phong' WHERE KIEU_DANG = @XETT;
	SELECT * FROM @XEMAY

	-- Y4
	DELETE FROM @XEMAY WHERE KIEU_DANG = 'Van Phong';
	SELECT * FROM @XEMAY;
END
