SELECT * FROM NGUOIDUNG
JOIN NHATRO ON NGUOIDUNG.ID_NGUOIDUNG = NHATRO.ID_NGUOIDUNG
JOIN LOAINHA ON LOAINHA.ID_LOAINHA = NHATRO.ID_LOAINHA 
JOIN DANHGIA ON DANHGIA.ID_NGUOIDUNG = NGUOIDUNG.ID_NGUOIDUNG