-- BIEN VO HUONG
--> KHONG CO TUONG TAC GIUA DB VA CLIENT
--> CAN CO BIEN DE GAN GIA TRI
/*
1. KHAI BAO BIEN
2. TRUYEN DL VAO BIEN
3. LAM VIEC VOI BIEN
--> VOI BIEN VO HUONG PHAI LAM Y HET 2 BUOC TREN
*/

-- KHAI BAO BIEN
--DECLARE @... DATTYPE

-- BIEN BANG
BEGIN
	DECLARE @SINHVIEN TABLE(
		MSV NVARCHAR(10),
		TEN NVARCHAR(50),
		TUOI INT
	)
END
DECLARE @COUNT INT  = 0
WHILE (@COUNT < 20)
	BEGIN
		SET @COUNT+=1
		INSERT INTO @SINHVIEN(MSV, TEN, TUOI)
		VALUES('PH00' + CONVERT(NVARCHAR, @COUNT), 'NGUYEN VAN ' + CONVERT(NVARCHAR, @COUNT), 18)
	END


SELECT * FROM @SINHVIEN



BEGIN
	DECLARE @NHANVIEN TABLE(
		MNV NCHAR(10) PRIMARY KEY NOT NULL,
		TEN NVARCHAR(50) NOT NULL,
		NGSINH DATE,
		LUONG INT
	)
	INSERT INTO @NHANVIEN(MNV, TEN, NGSINH, LUONG)
	VALUES
	('NV01', 'NGUYEN VAN A','2004-5-21', 1000),
	('NV02', 'NGUYEN VAN B','2004-6-23', 6000),
	('NV03', 'NGUYEN VAN C','2004-7-24', 5000),
	('NV04', 'NGUYEN VAN D','2004-8-25', 3000),
	('NV05', 'NGUYEN VAN E','2004-9-26', 4000),
	('NV06', 'NGUYEN VAN G','2004-10-7', 4000),
	('NV07', 'NGUYEN VAN H','2004-11-2', 6000)
	SELECT * FROM @NHANVIEN WHERE LUONG > 5000
END
DECLARE @GETLUONG INT
SELECT @GETLUONG = LUONG FROM @NHANVIEN
IF (@GETLUONG < 5000)
	BEGIN
		PRINT 'LUON > 5000'
	END
	
ELSE
	BEGIN
		PRINT 'LUONG < 500'
	END