/*
CAST: DUNG DE CHUYEN DOI KIEU DU LIEU NAY SANG KIEU DL KHAC
CAST(<DU LIEU> AS <KIEU DU LIEU>)
*/
--FOR EX
SELECT GETDATE()
SELECT N'HOM NAY LA: ' + CAST(GETDATE() AS VARCHAR)
SELECT N'HOM NAY CO ' + CAST(3 AS VARCHAR) + N' BAN NGHI'

/*
CONVERT: UPDATE OF "CAST" 
KHONG CHI NGAY THANG MA CON SU DUNG NHU CAST
CONVERT(<KIEU DL>, <DL>, <FORMAT>) VOI NGAY THANG
CONVERT(<KIEU DL>, <DL>) VOI DU LIEU BINH THUONG
*/
--DAY
SELECT CONVERT(VARCHAR, GETDATE(), 101)--MM/DD/YY
SELECT CONVERT(VARCHAR, GETDATE(), 103)--DD/MM/YY *
SELECT CONVERT(VARCHAR, GETDATE(), 105)--DD-MM-YY *
SELECT CONVERT(VARCHAR, GETDATE(), 107)--MOTH DD,YY
SELECT CONVERT(VARCHAR, GETDATE(), 110)--MM-DD-YY
SELECT CONVERT(VARCHAR, GETDATE(), 1)--MM/DD/YY
SELECT CONVERT(VARCHAR, GETDATE(), 0)--MOTH DD YY X:Y AM/PM
--FOR EX
SELECT N'HOM NAY LA' + CONVERT(NVARCHAR, GETDATE())

/*
PI: SO PI: PHAI CO () O CUOI
*/
--FOR EX
SELECT 6*6*PI()

/*
SQRT: CAN BAC HAI
*/
--FOR EX
SELECT SQRT(5)

/*
SQUARE: BINH PHUONG
SELECT SQUARE(5)
*/

/*
CEILING: LAM TRON LEN SO NGUYEN TIEP THEEO
SELECT CEILING(4.1) //5
*/


/*
FLOOR: NGUOC LAI VOI CEILING
SELECT FLOOR(4.9) //4
*/

/*
ROUND: LAM TRON DEN CHU SO THAP PHAN THU XXX
+ ROUND(<DL>, DO CHINH XAC)
TINH LUONG TB LAM TRON DEN SO THAP PHAN THU 2
+ SELECT ROUND(4999.1234567, 2)
SELECT PI()
SELECT ROUND(PI(), 6)
*/


/*
ABS: TRI TUYET DOI
+ ABS(<DL>)
SELECT ABS(-5) //5
SELECT ABS(SQRT(4)-SQUARE(9) + ROUND(PI(), 4)) //75.8584
*/

/*XU LY CHUOI*/
/*
LEN: DO DAI CHUOI
SELECT LEN('HELLO')
*/

/*
LTRIM AND RTRIM AND TRIM
SELECT LTRIM(' HELLO GUYS ')
SELECT RTRIM(' HELLO GUYS ')
SELECT TRIM(' HELLO GUYS ')-- CA HAI
*/

/*
LEFT: CAT CHUOI TU TRAI
LEFT('CHUOI', <VI TRI KET THUC>)
SELECT 'HELLO COM2034'
SELECT LEFT('HELLO COM2034', 5)
*/

/*
RIGHT: CAT CHUOI TU PHAI
RIGHT('CHUOI', <VI TRI KET THUC>)
SELECT 'HELLO COM2034'
SELECT RIGHT('HELLO COM2034', 4)
*/
/*
CREATE TABLE NHANVIEN(
	HO NVARCHAR(20),
	TENDEM NVARCHAR(20),
	TEN NVARCHAR(20)
)

*/

/*
CHARINDEX: TIM KIEM VI TRI CUA MOT HOAC CHUOI KY TU
*CHARINDEX(<K/CHUOI CAN TIM>, <CHUOI>)
SELECT CHARINDEX('COM2034', 'CHAO MUNG COM2034 KI SU23')

SELECT CHARINDEX(' ','IF YOU WANT')
*/

/*
SUBSTRING: CAT CHUOI
SUBSTRING('CHUOI', <VI TRI BAT DAU>, <DO DAI>)
SELECT SUBSTRING('HELLO CAC BAN', 2,4)

SELECT SUBSTRING('HELLO CAC BAN', CHARINDEX(' ', 'HELLO CAC BAN'), 4)
*/

/*
REPLACE: THAY THE KY TU HAOC CHUOI = KY TU KHAC
REPLACE(<'CHUOI'>, <KT TIM>, <KT THAY THE>)
SELECT REPLACE('0123-456-789', '-', '.')

SELECT REPLACE('CON CHO', 'CHO', 'MEO')
*/

/*
REVERSE: DAO NGUOC CHUOI
REVERSE(<'CHUOI'>)
SELECT REVERSE('LIVE')
SELECT REVERSE(0123456789)
*/

/*
UPPER
SELECT UPPER('hello')
LOWER
SELECT LOWER('HELLO')
*/

/*
SPACE: IN RA 12 DAU CACH
SELECT SPACE(12)
'            '
*/

 /*
DATENAME: LAY 1 PHAN THONG TIN CUA THOI GIAN
SELECT DATENAME(DAY, GETDATE()) AS DATE
SELECT DATENAME(MONTH, GETDATE()) AS MONTH
SELECT DATENAME(YEAR, GETDATE()) AS YEAR
SELECT DATENAME(DAYOFYEAR, GETDATE()) AS DAYOFYEAR
SELECT DATENAME(HOUR, GETDATE()) AS HOUR
SELECT DATENAME(WEEKDAY, GETDATE()) AS WEEKDAY
 */