USE AUTOINSERTDATA
GO
CREATE TABLE #TEMP(
	MANV NCHAR(10),
	STATUS NCHAR(10)
)
DECLARE @MA INT = 0
DECLARE @LUONG FLOAT = 100
DECLARE @COUNT INT = 0
WHILE(@COUNT < 20)
	BEGIN
		SET @MA += 1
		SET @LUONG += 100
		SET @COUNT+=1
		
		INSERT INTO NHANVIEN(MANV, LUONG)
		VALUES(CONVERT(NCHAR, @MA), @LUONG)
		PRINT @MA
	END

DECLARE @CHECK FLOAT
SELECT @CHECK = LUONG FROM NHANVIEN
DECLARE @LISTCOUNT INT
SELECT @LISTCOUNT = COUNT(*) FROM NHANVIEN
DECLARE @X INT = 0
DECLARE @STATUS NCHAR(10)

WHILE(@X <= @LISTCOUNT)
	BEGIN
		SET @X+=1
		PRINT @CHECK
		IF(@CHECK < 1110)
			BEGIN
			SET @STATUS = 'NGHEO'
			END
		ELSE
			BEGIN
				SET @STATUS = 'GIAU'
			END
		INSERT INTO #TEMP(MANV, STATUS)
		SELECT MANV, @STATUS FROM NHANVIEN WHERE MANV = @X
	END
SELECT NHANVIEN.MANV, NHANVIEN.LUONG, #TEMP.STATUS FROM NHANVIEN JOIN #TEMP ON NHANVIEN.MANV = #TEMP.MANV