/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GetUser;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

/**
 *
 * @author NONG HOANG VU
 */
public class User extends javax.swing.JFrame {

    ArrayList<ObjectUser> listUser = new ArrayList<>();

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUser = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnNhaTro = new javax.swing.JButton();
        btnFeedback = new javax.swing.JButton();
        btnLoaiTro = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUser.setText("Người Dùng");
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
        });

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Get Values"
            }
        ));
        jScrollPane2.setViewportView(tblUser);

        btnNhaTro.setText("Nhà Trọ");

        btnFeedback.setText("Đánh Giá");

        btnLoaiTro.setText("Loại Trọ");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnLoaiTro, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUser)
                    .addComponent(btnNhaTro)
                    .addComponent(btnFeedback)
                    .addComponent(btnLoaiTro)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //pas
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnUserMouseClicked
        String[] ten = { "NGUYEN VAN A", "TRAN THI B", "LE VAN C", "NGUYEN THI D", "PHAM VAN E", "TRAN THI F",
                "HOANG VAN G", "NGUYEN THI H", "LE VAN I", "PHAM THI K", "TRAN VAN L", "NGUYEN THI M", "LE VAN N",
                "PHAM THI O", "HOANG VAN P", "TRAN THI Q", "NGUYEN VAN S", "LE THI T", "HOANG VAN U", "PHAM THI V" };
        String[] gioiTinh = { "Nam", "Nu", "Nam", "Nu", "Nam", "Nu", "Nam", "Nu", "Nam", "Nu", "Nam", "Nu", "Nam", "Nu",
                "Nam", "Nu", "Nam", "Nu", "Nam", "Nu" };
        String[] diaChi = { "SO 10, DUONG TRAN DUY HUNG, QUAN CAU GIAY",
                "SO 20, DUONG NGUYEN CHI THANH, QUAN DONG DA",
                "SO 30, DUONG HAI BA TRUNG, QUAN HOAN KIEM",
                "SO 40, DUONG LANG, QUAN DONG DA",
                "SO 50, DUONG NGUYEN VAN CU, QUAN LONG BIEN",
                "SO 60, DUONG NGUYEN TRAI, QUAN THANH XUAN",
                "SO 70, DUONG HO TUNG MAU, QUAN CAU GIAY",
                "SO 80, DUONG DOI CAN, QUAN BA DINH",
                "SO 90, DUONG PHAM HUNG, QUAN NAM TU LIEM",
                "SO 100, DUONG NGUYEN VAN LINH, QUAN HA DONG",
                "SO 110, DUONG PHAM HUNG, QUAN NAM TU LIEM",
                "SO 120, DUONG TRAN DUY HUNG, QUAN CAU GIAY",
                "SO 130, DUONG LE VAN LUONG, QUAN THANH XUAN",
                "SO 140, DUONG NGUYEN VAN CU, QUAN LONG BIEN",
                "SO 150, DUONG PHAM HUNG, QUAN NAM TU LIEM",
                "SO 160, DUONG PHAM HUNG, QUAN NAM TU LIEM",
                "SO 170, DUONG TRAN DUY HUNG, QUAN CAU GIAY",
                "SO 180, DUONG NGUYEN CHI THANH, QUAN DONG DA",
                "SO 190, DUONG HO TUNG MAU, QUAN CAU GIAY",
                "SO 200, DUONG TRAN DUY HUNG, QUAN CAU GIAY" };
        String[] quan = { "CAU GIAY", "DONG DA", "HOAN KIEM", "DONG DA", "LONG BIEN", "THANH XUAN", "CAU GIAY",
                "BA DINH", "NAM TU LIEM", "HA DONG", "NAM TU LIEM", "CAU GIAY", "THANH XUAN", "LONG BIEN",
                "NAM TU LIEM", "NAM TU LIEM", "CAU GIAY", "DONG DA", "CAU GIAY", "CAU GIAY" };
        String[] sdt = { "0987654321", "0123456789", "0909090909", "0912345678", "0987123456", "0909090909",
                "0912345678", "0987123456", "0909090909", "0912345678", "0987123456", "0909090909", "0912345678",
                "0987123456", "0909090909", "0912345678", "0987123456", "0909090909", "0912345678", "0987123456" };
        String[] email = { "VAN.A@gmail.com", "THI.B@gmail.com", "VAN.C@gmail.com", "THI.D@gmail.com",
                "VAN.E@gmail.com", "THI.F@gmail.com", "VAN.G@gmail.com", "THI.H@gmail.com", "VAN.I@gmail.com",
                "THI.K@gmail.com", "VAN.L@gmail.com", "THI.M@gmail.com", "VAN.N@gmail.com", "THI.O@gmail.com",
                "VAN.P@gmail.com", "THI.Q@gmail.com", "VAN.S@gmail.com", "THI.T@gmail.com", "VAN.U@gmail.com",
                "THI.V@gmail.com" };

        for (int i = 0; i < ten.length; i++) {
            ObjectUser user = new ObjectUser();
            user.setName(ten[i]);
            user.setGender(gioiTinh[i]);
            user.setAddress(diaChi[i]);
            user.setQuan(quan[i]);
            user.setSdt(sdt[i]);
            user.setEmail(email[i]);
            listUser.add(user);
        }
        DefaultTableModel tblModel = (DefaultTableModel) tblUser.getModel();
        int id = 0;
        for (ObjectUser objectUser : listUser) {
            id++;
            String[] rows = { "('" + id + "', '" + objectUser.getName() + "', '" + objectUser.getGender() + "', '"
                    + objectUser.getSdt() + "', '" + objectUser.getAddress() + "', '" + objectUser.getQuan() + "', '"
                    + objectUser.getEmail() + "')," };
            tblModel.addRow(rows);
        }
    }// GEN-LAST:event_btnUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnLoaiTro;
    private javax.swing.JButton btnNhaTro;
    private javax.swing.JButton btnUser;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblUser;
    // End of variables declaration//GEN-END:variables
}
